#!/usr/bin/env ruby
require 'json'
require 'awesome_print'
require 'rexml/document'
require_relative 'parser'
require_relative 'utils'
require_relative 'settings'

require 'pry'

include REXML
include Utils

Utils::LOG = true
l 'start..'

unless ARGV.empty?
  OUTPUT_PATH = output_path_create(cli_options)

  l OUTPUT_PATH , :output_path
  l ARGV
  #convert(ARGV)
else
  puts print_help
  exit 0

end

